baseURL = 'https://github.com/KatieUmbra/sandbox-blog'
languageCode = 'en-us'
title = "Katherine's Sandbox Blog"
theme = 'writeonlyhugo-theme'
sectionPagesMenu = "main"
tableOfContents = true

[markup]
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 3

[taxonomies]
tags = "tags"